GET http://127.0.0.1:8000/api/categoria
Authorization: Bearer 47|gey02pGtSk23GRmYpywQhM7O1wPTk7WWB1kZUXNi72b40638

### guardar
POST http://127.0.0.1:8000/api/categoria
Authorization: Bearer 47|gey02pGtSk23GRmYpywQhM7O1wPTk7WWB1kZUXNi72b40638
Content-Type: application/json
Accept: application/json

{
    "nombre": "ROPA"
}

### 
GET http://127.0.0.1:8000/api/categoria/3
Authorization: Bearer 1|JGEZFuKlk7Y99ZdPOPkqf9xe8CuiVlygD3pK5Ja16c1f7b74
Accept: application/json

### modificar
PUT http://127.0.0.1:8000/api/categoria/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer 3|WaComik1rMCwjL3XPXxL5SticpVvRDxrRbxV7lv17f9bd34c

{
    "nombre": "ROPA",
    "detalle": "Ropa para damas"
}

### eliminar
DELETE http://127.0.0.1:8000/api/categoria/4
Accept: application/json
Authorization: Bearer 3|WaComik1rMCwjL3XPXxL5SticpVvRDxrRbxV7lv17f9bd34c
