GET http://127.0.0.1:8000/api/categoria
Authorization: Bearer 1|JGEZFuKlk7Y99ZdPOPkqf9xe8CuiVlygD3pK5Ja16c1f7b74

### guardar
POST http://127.0.0.1:8000/api/categoria
Authorization: Bearer 1|JGEZFuKlk7Y99ZdPOPkqf9xe8CuiVlygD3pK5Ja16c1f7b74
Content-Type: application/json
Accept: application/json

{
    "nombre": "ELECTRODOMESTOS"
}

### 
GET http://127.0.0.1:8000/api/categoria/4
Authorization: Bearer 1|JGEZFuKlk7Y99ZdPOPkqf9xe8CuiVlygD3pK5Ja16c1f7b74
Accept: application/json
