GET http://127.0.0.1:8000/api/producto?limit=5&page=2&q=
Authorization: Bearer 2|idkK44QDvqb4wYwA9QYlkhhTImR17EAUyOyjgYCP724da853


### guardar
POST http://127.0.0.1:8000/api/producto
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|idkK44QDvqb4wYwA9QYlkhhTImR17EAUyOyjgYCP724da853

{
    "nombre": "CAMISA",
    "precio": 299.98,
    "stock": 12,
    "estado": true,
    "descripcion": "Camisa Talla Grande",
    "categoria_id": 2
}

###

GET http://127.0.0.1:8000/api/producto/4
Authorization: Bearer 2|idkK44QDvqb4wYwA9QYlkhhTImR17EAUyOyjgYCP724da853
