GET http://127.0.0.1:8000/api/producto?limit=5&page=1&q=
Authorization: Bearer 46|NwUnpkJWqAZ4pcS9v1ftFTplNroO1JYK1CCjBul0ec02f807


### guardar
POST http://127.0.0.1:8000/api/producto
Content-Type: application/json
Accept: application/json
Authorization: Bearer 47|gey02pGtSk23GRmYpywQhM7O1wPTk7WWB1kZUXNi72b40638

{
    "nombre": "PANTALON",
    "precio": 199.98,
    "stock": 20,
    "estado": true,
    "descripcion": "Pantalon Grande",
    "categoria_id": 1
}

###

GET http://127.0.0.1:8000/api/producto/4
Authorization: Bearer 2|idkK44QDvqb4wYwA9QYlkhhTImR17EAUyOyjgYCP724da853
